# -*- coding: utf-8 -*-
"""deploying_docker_to_GKE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZZz9lGRKo4OtwQgnMDVwgqNMeJtBnev
"""

#!/bin/bash

# Set variables
PROJECT_ID="axial-app-435805-e3"
CLUSTER_NAME="stock-recommendation-cluster"
ZONE="us-east1"
DOCKER_IMAGE_NAME="stock-recommendation-app"
DOCKER_IMAGE_TAG="latest"
GCR_IMAGE="gcr.io/$PROJECT_ID/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
K8S_DEPLOYMENT_NAME="stock-recommendation-app"
K8S_SERVICE_NAME="stock-recommendation-app-service"

# Step 1: Authenticate with Google Cloud
gcloud auth login

gcloud config set project $PROJECT_ID

gcloud auth configure-docker

# Step 2: Build and push Docker image to Google Container Registry (GCR)
docker build -t $GCR_IMAGE .
docker push $GCR_IMAGE

# Step 3: Create a GKE cluster (if not already created)
gcloud container clusters create $CLUSTER_NAME \
    --zone $ZONE \
    --num-nodes=3

# Step 4: Authenticate kubectl with the GKE cluster
gcloud container clusters get-credentials $CLUSTER_NAME --zone $ZONE

# Step 5: Create Kubernetes deployment
kubectl create deployment $K8S_DEPLOYMENT_NAME --image=$GCR_IMAGE

# Step 6: Expose the deployment as a service
kubectl expose deployment $K8S_DEPLOYMENT_NAME \
    --type=LoadBalancer \
    --port=80 \
    --target-port=5000

# Step 7: Verify the deployment
kubectl get services