# -*- coding: utf-8 -*-
"""Docker_containerization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvALECMedvBOy6mLtz4nSn8d-26deVfk
"""

# Step 1: Use an official Python runtime as the base image
FROM python:3.9-slim

# Step 2: Set the working directory in the container
WORKDIR /app

# Step 3: Copy the application's code to the working directory
COPY . /app

# Step 4: Install any required dependencies (assuming requirements.txt exists)
RUN pip install --no-cache-dir -r requirements.txt

# Step 5: Expose the port the app runs on (optional, replace 5000 with your app’s port)
EXPOSE 5000

# Step 6: Command to run the application
CMD ["python", "app.py"]